name: login
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  datetime_picker_formfield: ^1.0.0
  simple_animations: ^1.3.3

  cupertino_icons: ^0.1.2
  flutter_datetime_picker: ^1.3.8
  intl: ^0.15.8
  http: ^0.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
